m1 = int(input("Enter Marks of Student Number 1: "))
m2 = int(input("Enter Marks of Student Number 2: "))
m2 = int(input("Enter Marks of Student Number 2: "))
m3 = int(input("Enter Marks of Student Number 3: "))
m4 = int(input("Enter Marks of Student Number 4: "))
m5 = int(input("Enter Marks of Student Number 5: "))
m6 = int(input("Enter Marks of Student Number 6: "))
studentlist = [m1,m2,m3,m4,m5,m6]
studentlist.sort()
print(studentlist)